/*
====================================================
File: src/server/instructors.ts
====================================================
*/

export interface InstructorsEnv { DB: D1Database; }
export interface InstructorRecord {
  id:number; slug:string; firstName:string; lastName:string; phone:string; email:string;
  specialty:string; instruments:string[]; biography:string; notes:string; isActive:boolean;
  createdAt:string; updatedAt:string;
}
interface InstructorRow { id:number; slug:string; first_name:string; last_name:string; phone:string; email:string; specialty:string; instruments:string; biography:string; notes:string; is_active:number; created_at:string; updated_at:string; }
function parseInstruments(raw:string):string[]{try{const p=JSON.parse(raw);return Array.isArray(p)?p.filter(x=>typeof x==="string"):[]}catch{return[]}}
function mapInstructorRow(row:InstructorRow):InstructorRecord{return{id:row.id,slug:row.slug,firstName:row.first_name,lastName:row.last_name,phone:row.phone,email:row.email,specialty:row.specialty,instruments:parseInstruments(row.instruments),biography:row.biography,notes:row.notes,isActive:row.is_active===1,createdAt:row.created_at,updatedAt:row.updated_at}}
const INSTRUCTOR_COLUMNS="id, slug, first_name, last_name, phone, email, specialty, instruments, biography, notes, is_active, created_at, updated_at";
export interface InstructorListParams{search?:string|null;status?:string|null;page?:number|null;pageSize?:number|null}
export interface NormalizedInstructorListParams{search:string;isActive:boolean|null;page:number;pageSize:number;offset:number}
const DEFAULT_PAGE_SIZE=20,MAX_PAGE_SIZE=100;
export function normalizeInstructorListParams(params:InstructorListParams):NormalizedInstructorListParams{const search=(params.search??"").trim();const isActive=params.status==="active"?true:params.status==="inactive"?false:null;const page=Math.max(1,Number.isFinite(params.page)?Math.floor(params.page as number):1);const pageSize=Math.min(MAX_PAGE_SIZE,Math.max(1,Number.isFinite(params.pageSize)?Math.floor(params.pageSize as number):DEFAULT_PAGE_SIZE));return{search,isActive,page,pageSize,offset:(page-1)*pageSize}}
export interface InstructorListItem extends InstructorRecord{studentCount:number}
export interface InstructorListResult{instructors:InstructorListItem[];total:number;page:number;pageSize:number}
export async function listInstructors(db:D1Database,rawParams:InstructorListParams):Promise<InstructorListResult>{const{search,isActive,page,pageSize,offset}=normalizeInstructorListParams(rawParams);const where:string[]=[];const bind:unknown[]=[];if(isActive!==null){where.push("is_active = ?");bind.push(isActive?1:0)}if(search){where.push("((first_name || ' ' || last_name) LIKE ? OR specialty LIKE ? OR phone LIKE ?)");bind.push(`%${search}%`,`%${search}%`,`%${search}%`)}const whereSql=where.length?`WHERE ${where.join(" AND ")}`:"";const totalRow=await db.prepare(`SELECT COUNT(*) as count FROM instructors ${whereSql}`).bind(...bind).first<{count:number}>();const rows=await db.prepare(`SELECT ${INSTRUCTOR_COLUMNS},(SELECT COUNT(DISTINCT r.student_national_code) FROM registrations r WHERE r.instructor_id=instructors.id AND r.student_national_code IS NOT NULL AND r.student_national_code!='') as student_count FROM instructors ${whereSql} ORDER BY is_active DESC, first_name, last_name LIMIT ? OFFSET ?`).bind(...bind,pageSize,offset).all<InstructorRow&{student_count:number}>();return{instructors:rows.results.map(row=>({...mapInstructorRow(row),studentCount:row.student_count})),total:totalRow?.count??0,page,pageSize}}
export interface InstructorStudentSummary{studentId:number;firstName:string;lastName:string;nationalCode:string;studentStatus:string;course:string;termCount:number;startDate:string;lastActivity:string}
export interface InstructorProfile{instructor:InstructorRecord;students:InstructorStudentSummary[]}
export async function getInstructorProfile(db:D1Database,id:number):Promise<InstructorProfile|null>{const row=await db.prepare(`SELECT ${INSTRUCTOR_COLUMNS} FROM instructors WHERE id = ?`).bind(id).first<InstructorRow>();if(!row)return null;let students:InstructorStudentSummary[]=[];try{const result=await db.prepare(`SELECT s.id as student_id,s.first_name,s.last_name,s.national_code,s.status as student_status,r.instrument_title as course,COUNT(*) as term_count,MIN(r.created_at) as start_date,MAX(r.created_at) as last_activity FROM registrations r JOIN students s ON s.id=r.student_id WHERE r.instructor_id=? GROUP BY s.id,r.instrument_title ORDER BY last_activity DESC`).bind(id).all<any>();students=result.results.map(s=>({studentId:s.student_id,firstName:s.first_name,lastName:s.last_name,nationalCode:s.national_code,studentStatus:s.student_status,course:s.course,termCount:s.term_count,startDate:s.start_date,lastActivity:s.last_activity}))}catch(error){console.error("[admin/instructors] profile student query failed",error)}return{instructor:mapInstructorRow(row),students}}
const EMAIL_RE=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export interface InstructorInput{firstName?:string;lastName?:string;phone?:string;email?:string;specialty?:string;instruments?:string[];biography?:string;notes?:string;isActive?:boolean}
export interface ValidationResult{valid:boolean;errors:string[]}
export function validateInstructorInput(input:InstructorInput,{isCreate=false}:{isCreate?:boolean}={}):ValidationResult{const errors:string[]=[];if(isCreate&&!input.firstName?.trim())errors.push("نام مدرس الزامی است.");if(isCreate&&!input.lastName?.trim())errors.push("نام خانوادگی مدرس الزامی است.");if(input.email!==undefined&&input.email!==""&&!EMAIL_RE.test(input.email))errors.push("ایمیل معتبر نیست.");if(input.instruments!==undefined&&!Array.isArray(input.instruments))errors.push("فهرست سازهای آموزشی معتبر نیست.");return{valid:errors.length===0,errors}}
function slugify(firstName:string,lastName:string):string{const base=`${firstName}-${lastName}`.trim().toLowerCase().replace(/\s+/g,"-").replace(/[^a-z0-9\u0600-\u06FF-]/g,"");return base||`instructor-${Date.now()}`}
export async function createInstructor(db:D1Database,input:InstructorInput):Promise<number>{const inserted=await db.prepare(`INSERT INTO instructors (slug, first_name, last_name, phone, email, specialty, instruments, biography, notes, is_active) VALUES (?,?,?,?,?,?,?,?,?,1)`).bind(slugify(input.firstName??"",input.lastName??""),input.firstName??"",input.lastName??"",input.phone??"",input.email??"",input.specialty??"",JSON.stringify(input.instruments??[]),input.biography??"",input.notes??"").run();if(typeof inserted.meta.last_row_id!=="number")throw new Error("Failed to create instructor");return inserted.meta.last_row_id}
const PATCHABLE_COLUMNS:Partial<Record<keyof InstructorInput,string>>={firstName:"first_name",lastName:"last_name",phone:"phone",email:"email",specialty:"specialty",biography:"biography",notes:"notes"};
export async function updateInstructor(db:D1Database,id:number,patch:InstructorInput):Promise<boolean>{const setClauses:string[]=[];const bind:unknown[]=[];for(const[key,column]of Object.entries(PATCHABLE_COLUMNS)as[keyof InstructorInput,string][]{const value=patch[key];if(value!==undefined){setClauses.push(`${column} = ?`);bind.push(value)}}if(patch.instruments!==undefined){setClauses.push("instruments = ?");bind.push(JSON.stringify(patch.instruments))}if(patch.isActive!==undefined){setClauses.push("is_active = ?");bind.push(patch.isActive?1:0)}if(!setClauses.length)return true;const result=await db.prepare(`UPDATE instructors SET ${setClauses.join(", ")}, updated_at=datetime('now') WHERE id=?`).bind(...bind,id).run();return result.success}
