export const prerender=false;
import type {APIRoute} from "astro";
import {env} from "cloudflare:workers";
import {requireRole,ROLES,json,type AdminEnv} from "../../../server/admin-auth";
import {buildCertificateHtml,type CertificateData} from "../../../server/certificates/template";
interface Req{registration_id:number;book_id?:number;national_id:string;completion_date_jalali:string;level?:string;curriculum_note?:string}
interface R{tracking_code:string;instrument_title:string;instrument_slug:string;instructor_name:string;student_first_name:string;student_last_name:string;student_gender:string|null;student_national_code:string|null}
interface B{title:string;author:string|null;cover_image:string|null}
function honor(g:string|null):"آقای"|"خانم"{return ["female","زن","دختر"].includes((g??"").trim().toLowerCase())?"خانم":"آقای"}
async function image(request:Request,path:string){const assets=(env as unknown as {ASSETS?:{fetch:(r:Request)=>Promise<Response>}}).ASSETS;if(!assets?.fetch)throw Error("ASSETS binding در Worker تنظیم نشده است.");const u=new URL(path,request.url),res=await assets.fetch(new Request(u));if(!res.ok)throw Error(`تصویر ساز پیدا نشد (${res.status})`);const bytes=new Uint8Array(await res.arrayBuffer());let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return `data:${res.headers.get("content-type")||"image/png"};base64,${btoa(s)}`}
function level(l:string){return ({"1":"مقدماتی","2":"متوسط","3":"پیشرفته","4":"عالی"} as Record<string,string>)[l]||"مقدماتی"}
export const POST:APIRoute=async({request})=>{const denied=await requireRole(request,env as AdminEnv,[ROLES.ADMIN]);if(denied)return denied;const db=env.DB,browser=(env as unknown as {BROWSER?:unknown}).BROWSER;if(!browser)return json({success:false,message:"BROWSER binding تنظیم نشده است."},503);const b=await request.json() as Req;if(!b.registration_id||!b.national_id||!b.completion_date_jalali)return json({success:false,message:"شناسه ثبت‌نام، کد ملی و تاریخ پایان دوره الزامی هستند."},422);const r=await db.prepare("SELECT tracking_code,instrument_title,instrument_slug,instructor_name,student_first_name,student_last_name,student_gender,student_national_code FROM registrations WHERE id=?").bind(b.registration_id).first<R>();if(!r)return json({success:false,message:"ثبت‌نامی پیدا نشد."},404);if(r.student_national_code&&r.student_national_code!==b.national_id)return json({success:false,message:"کد ملی با اطلاعات هنرجو مطابقت ندارد."},422);let book:B|null=null;if(b.book_id)book=await db.prepare("SELECT title,author,cover_image FROM course_books WHERE id=?").bind(b.book_id).first<B>();let photo:string;try{photo=await image(request,`/images/cert-photos/${r.instrument_slug}.png`)}catch(e){return json({success:false,message:`بارگذاری تصویر ساز شکست خورد: ${e instanceof Error?e.message:String(e)}`},502)}const data:CertificateData={title:"گواهی پایان دوره",disciplineLine:`نوازندگی ${r.instrument_title.replace(/^آموزش\s+/,"")}${b.level?" دوره "+level(b.level):""}`,certNumber:r.tracking_code,level:b.level??null,honorific:honor(r.student_gender),studentName:`${r.student_first_name} ${r.student_last_name}`.trim(),nationalId:b.national_id,completionDateJalali:b.completion_date_jalali,bookTitle:book?.title??null,bookAuthor:book?.author??null,curriculumNote:b.curriculum_note??null,bookCoverUrl:book?.cover_image?`https://fatehmusic.ir/images/books/${book.cover_image}`:null,instructorLabel:`مدرس ${r.instrument_title.replace(/^آموزش\s+/,"")}`,instructorName:r.instructor_name,instrumentPhotoUrl:photo,logoUrl:"https://fatehmusic.ir/logo.png"};
await db.prepare("INSERT INTO issued_certificates (registration_id,national_code,cert_number,completion_date_jalali,level,book_id,curriculum_note) VALUES (?,?,?,?,?,?,?) ON CONFLICT(cert_number) DO UPDATE SET national_code=excluded.national_code,completion_date_jalali=excluded.completion_date_jalali,level=excluded.level,book_id=excluded.book_id,curriculum_note=excluded.curriculum_note").bind(b.registration_id,b.national_id,r.tracking_code,b.completion_date_jalali,b.level??null,b.book_id??null,b.curriculum_note??null).run();
try{const pdf=await (browser as any).quickAction("pdf",{html:buildCertificateHtml(data),pdfOptions:{format:"a4",landscape:true,margin:{top:0,bottom:0,left:0,right:0},printBackground:true,preferCSSPageSize:false,displayHeaderFooter:false,scale:1}});const bytes:ArrayBuffer=pdf instanceof Response?await pdf.arrayBuffer():pdf;return new Response(bytes,{status:200,headers:{"Content-Type":"application/pdf","Content-Disposition":`inline; filename="certificate-${r.tracking_code}.pdf"`}})}catch(e){return json({success:false,message:`تولید PDF شکست خورد: ${e instanceof Error?e.message:String(e)}`},500)}};
