export const prerender = false;

import type { APIRoute } from "astro";
import { env } from "cloudflare:workers";
import { requireRole, ROLES, json, type AdminEnv } from "../../../server/admin-auth";
import { getStudentSession, type StudentEnv } from "../../../server/student-auth";
import { buildContract, type RegistrationState } from "../../../scripts/registration/ContractTemplates";
import { getCurrentJalaliYear } from "../../../utils/format-date";

interface RegistrationRow { id:number; tracking_code:string; instrument_title:string; instrument_slug:string; instrument_type:string|null; instructor_name:string; instructor_id:number|null; schedule_id:number|null; schedule_weekday:string|null; schedule_duration:number|null; schedule_classroom:string|number|null; schedule_class_mode:string|null; student_first_name:string; student_last_name:string; student_national_code:string|null; student_mobile:string; student_age:number|null; student_gender:string|null; student_has_instrument:string|null; student_father_name:string|null; student_id_issue_place:string|null; student_birth_year:number|null; student_occupation:string|null; student_address:string|null; }
function normalizeGender(v:string|null):RegistrationState["student"]["gender"]{const g=(v??"").trim().toLowerCase();if(["female","زن","دختر"].includes(g))return "female";if(["male","مرد","پسر"].includes(g))return "male";return null}
function escapeHtml(v:string){return v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;")}
function renderContractHtml(contract:NonNullable<ReturnType<typeof buildContract>>,r:RegistrationRow){const blocks=contract.blocks.map((b,i)=>`<section class="contract-block${i===0?" intro-block":""}${b.heading?.startsWith("ماده ۳")?" tuition-block":""}">${b.heading?`<h2>${escapeHtml(b.heading)}</h2>`:""}${b.paragraphs.map(p=>`<p>${escapeHtml(p)}</p>`).join("")}</section>`).join("");return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><style>@page{size:A4;margin:10mm 12mm 12mm}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff;color:#292722;font-family:Tahoma,Arial,sans-serif}body{font-size:10.8pt;line-height:1.9}.sheet{min-height:275mm;border:1.1px solid #b99742;background:#fffefa;padding:10mm 11mm 9mm}.header{text-align:center;padding:3mm 8mm 5mm;margin-bottom:5mm;border-bottom:1px solid #d8c68c}.brand{color:#9b761f;font-weight:700;font-size:12pt}.title{margin:1mm 0;font-size:24pt;font-weight:700;color:#171717}.subtitle{color:#756b58;font-size:8.8pt}.meta{display:grid;grid-template-columns:1fr 1fr;gap:4mm;margin-top:4mm}.meta-item{padding:2.3mm 4mm;border:1px solid #ded4b9;border-radius:5px;background:#fffdf6;color:#675e4e;font-size:8.8pt}.meta-item strong{color:#80631d;margin-inline-start:2mm}.contract-block{margin:0 0 3.2mm;padding:3.5mm 5mm 3mm;border:1px solid #e4dcc7;border-radius:5px;background:#fff}.contract-block h2{margin:0 0 1.5mm;padding-bottom:1.5mm;border-bottom:1px solid #eee7d5;color:#7f611b;font-size:11.2pt}.contract-block p{margin:0 0 1.4mm;text-align:justify}.intro-block{border:0;background:transparent;text-align:center}.intro-block p{text-align:center;color:#655a48;font-size:9.4pt}.tuition-block{border-color:#cdb875;background:#fbf5e3}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:35mm;margin-top:8mm}.signature{min-height:30mm;padding-top:8mm;text-align:center;color:#635b4d;font-size:9pt}.signature strong{display:block;margin-top:2mm;color:#292722;font-size:10.2pt}.footer{margin-top:2mm;padding-top:2.5mm;border-top:.6px solid #d7c486;text-align:center;color:#877c68;font-size:7.7pt}</style></head><body><div class="sheet"><header class="header"><div class="brand">آموزشگاه موسیقی فاتح</div><div class="title">قرارداد هنرجویی</div><div class="subtitle">قرارداد رسمی ثبت‌نام و تعهدات آموزشی</div><div class="meta"><div class="meta-item"><strong>کد پیگیری</strong>${escapeHtml(r.tracking_code)}</div><div class="meta-item"><strong>تاریخ تنظیم</strong>${escapeHtml(contract.signature.date)}</div></div></header>${blocks}<div class="signatures"><div class="signature">امضای هنرجو / ولی و سرپرست<strong>${escapeHtml(contract.signature.studentName)}</strong></div><div class="signature">مدیر آموزشگاه<strong>رضا فاتح</strong></div></div><div class="footer">آموزشگاه موسیقی فاتح · شوشتر · قرارداد ثبت‌نام هنرجو</div></div></body></html>`}

export const POST:APIRoute=async({request})=>{
 const adminDenied=await requireRole(request,env as AdminEnv,[ROLES.ADMIN,ROLES.REGISTRAR]);
 const student=await getStudentSession(request,env as StudentEnv);
 if(adminDenied && !student)return adminDenied;
 const db=env.DB,browser=(env as unknown as {BROWSER?:unknown}).BROWSER;if(!db)return json({success:false,message:"دیتابیس در دسترس نیست."},503);if(!browser)return json({success:false,message:"BROWSER binding تنظیم نشده است."},503);
 const body=(await request.json().catch(()=>({}))) as {registration_id?:number};if(!body.registration_id)return json({success:false,message:"شناسه ثبت‌نام الزامی است."},422);
 const r=await db.prepare(`SELECT id,tracking_code,instrument_title,instrument_slug,instrument_type,instructor_name,instructor_id,schedule_id,schedule_weekday,schedule_duration,schedule_classroom,schedule_class_mode,student_first_name,student_last_name,student_national_code,student_mobile,student_age,student_gender,student_has_instrument,student_father_name,student_id_issue_place,student_birth_year,student_occupation,student_address FROM registrations WHERE id=?`).bind(body.registration_id).first<RegistrationRow>();
 if(!r)return json({success:false,message:"ثبت‌نامی با این شناسه پیدا نشد."},404);if(student&&r.student_national_code!==student.nationalCode)return json({success:false,message:"دسترسی به این قرارداد مجاز نیست."},403);
 const prior=r.student_national_code?await db.prepare("SELECT COUNT(*) AS count FROM registrations WHERE student_national_code=? AND id<=?").bind(r.student_national_code,r.id).first<{count:number}>():null;const term=Math.max(1,Number(prior?.count??1));
 const state:RegistrationState={currentStep:"success",selection:{instrument:{id:r.id,slug:r.instrument_slug,title:r.instrument_title,type:r.instrument_type},instructor:{id:r.instructor_id,name:r.instructor_name,auto:false},schedule:{id:r.schedule_id,weekday:r.schedule_weekday,sessionDuration:r.schedule_duration,classroom:r.schedule_classroom,classMode:r.schedule_class_mode,auto:false}},student:{firstName:r.student_first_name,lastName:r.student_last_name,nationalCode:r.student_national_code??"",mobile:r.student_mobile,age:r.student_age,gender:normalizeGender(r.student_gender),hasInstrument:r.student_has_instrument==="yes"?"yes":r.student_has_instrument==="no"?"no":null,fatherName:r.student_father_name??"",idIssuePlace:r.student_id_issue_place??"",birthYear:r.student_birth_year||getCurrentJalaliYear()-(r.student_age??0),occupation:r.student_occupation??"",address:r.student_address??""},trackingCode:r.tracking_code,term,completed:true};
 const contract=buildContract(state);if(!contract)return json({success:false,message:"اطلاعات ثبت‌نام برای تولید قرارداد کامل نیست."},422);
 try{const pdfResult=await (browser as any).quickAction("pdf",{html:renderContractHtml(contract,r)});const pdfBytes:ArrayBuffer=pdfResult instanceof Response?await pdfResult.arrayBuffer():pdfResult;return new Response(pdfBytes,{status:200,headers:{"Content-Type":"application/pdf","Content-Disposition":`inline; filename="contract-${r.tracking_code}.pdf"`}})}catch(e){return json({success:false,message:`تولید PDF قرارداد شکست خورد: ${e instanceof Error?e.message:String(e)}`},500)}
};
