import {buildCertificateHtml,type CertificateData} from "./template";

type Db=any;type Browser=any;type Assets={fetch:(request:Request)=>Promise<Response>};
export type CertificateType="course_completion"|"concert_participation"|"student_performance"|"workshop_participation";
export interface CertificateGenerateInput{registration_id:number;national_id:string;certificate_type?:CertificateType;completion_date_jalali:string;level?:string|null;book_id?:number|null;curriculum_note?:string|null;event_title?:string|null;event_date_jalali?:string|null;event_role?:string|null;event_details?:string|null;event_instructor?:string|null;workshop_hours?:string|null;}
interface Registration{tracking_code:string;instrument_title:string;instrument_slug:string;instructor_name:string;student_first_name:string;student_last_name:string;student_gender:string|null;student_national_code:string|null}
interface Book{title:string;author:string|null;cover_image:string|null}
function honor(g:string|null):"آقای"|"خانم"{return ["female","زن","دختر"].includes((g??"").trim().toLowerCase())?"خانم":"آقای"}
function level(l:string){return ({"1":"مقدماتی","2":"متوسط","3":"پیشرفته","4":"عالی"} as Record<string,string>)[l]||"مقدماتی"}
async function image(request:Request,assets:Assets,slug:string){const names=[`${slug}.png`,`${slug}-course.png`,slug==="santur"?"santur-course.png":""];for(const name of names){if(!name)continue;const u=new URL(`/images/cert-photos/${name}`,request.url);const res=await assets.fetch(new Request(u));if(!res.ok)continue;const bytes=new Uint8Array(await res.arrayBuffer());let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return `data:${res.headers.get("content-type")||"image/png"};base64,${btoa(s)}`}throw Error(`تصویر ساز پیدا نشد (slug: ${slug})`)}
async function qrCodeDataUrl(verificationUrl:string){const res=await fetch(`https://quickchart.io/qr?text=${encodeURIComponent(verificationUrl)}&size=360&margin=2&ecLevel=H`);if(!res.ok)throw Error(`تولید QR Code شکست خورد (${res.status})`);const bytes=new Uint8Array(await res.arrayBuffer());let s="";for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return `data:${res.headers.get("content-type")||"image/png"};base64,${btoa(s)}`}
export async function generateCertificatePdf(request:Request,db:Db,browser:Browser,assets:Assets,b:CertificateGenerateInput){
 const type=b.certificate_type||"course_completion";
 if(!b.registration_id||!b.national_id||!b.completion_date_jalali)throw Object.assign(new Error("شناسه ثبت‌نام، کد ملی و تاریخ الزامی هستند."),{status:422});
 const r=await db.prepare("SELECT tracking_code,instrument_title,instrument_slug,instructor_name,student_first_name,student_last_name,student_gender,student_national_code FROM registrations WHERE id=?").bind(b.registration_id).first<Registration>();
 if(!r)throw Object.assign(new Error("ثبت‌نامی پیدا نشد."),{status:404});
 if(r.student_national_code&&r.student_national_code!==b.national_id)throw Object.assign(new Error("کد ملی با اطلاعات هنرجو مطابقت ندارد."),{status:422});
 let book:Book|null=null;if(b.book_id)book=await db.prepare("SELECT title,author,cover_image FROM course_books WHERE id=?").bind(b.book_id).first<Book>();
 const photo=await image(request,assets,String(r.instrument_slug||"").trim().toLowerCase());
 const qr=await qrCodeDataUrl(`https://fatehmusic.ir/certificate/verify?number=${encodeURIComponent(r.tracking_code)}`);
 const data:CertificateData={type,title:type==="course_completion"?"گواهی پایان دوره":type==="concert_participation"?"گواهی شرکت در کنسرت":type==="student_performance"?"گواهی اجرای هنرجویی":"گواهی شرکت در کارگاه",disciplineLine:`${type==="workshop_participation"?"کارگاه":"رشته"} ${type==="course_completion"?`نوازندگی ${r.instrument_title.replace(/^آموزش\s+/,"")}${b.level?" دوره "+level(b.level):""}`:(b.event_title||r.instrument_title)}`,certNumber:r.tracking_code,level:b.level??null,honorific:honor(r.student_gender),studentName:`${r.student_first_name} ${r.student_last_name}`.trim(),nationalId:b.national_id,completionDateJalali:b.completion_date_jalali,bookTitle:book?.title??null,bookAuthor:book?.author??null,curriculumNote:b.curriculum_note??null,bookCoverUrl:type==="course_completion"&&book?.cover_image?`https://fatehmusic.ir/images/books/${book.cover_image}`:null,instructorLabel:type==="workshop_participation"?"مدرس کارگاه":`مدرس ${r.instrument_title.replace(/^آموزش\s+/,"")}`,instructorName:b.event_instructor||r.instructor_name,instrumentPhotoUrl:photo,logoUrl:"https://fatehmusic.ir/logo.png",qrCodeUrl:qr,eventTitle:b.event_title??null,eventDateJalali:b.event_date_jalali??b.completion_date_jalali,eventRole:b.event_role??null,eventDetails:b.event_details??null,workshopHours:b.workshop_hours??null};
 const pdf=await browser.quickAction("pdf",{html:buildCertificateHtml(data),pdfOptions:{format:"a4",landscape:true,margin:{top:0,bottom:0,left:0,right:0},printBackground:true,preferCSSPageSize:false,displayHeaderFooter:false,scale:1}});const bytes:ArrayBuffer=pdf instanceof Response?await pdf.arrayBuffer():pdf;return new Response(bytes,{status:200,headers:{"Content-Type":"application/pdf","Content-Disposition":`inline; filename="certificate-${r.tracking_code}.pdf"`}});
}
